require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RolesController do

  def mock_role(stubs={})
    @mock_role ||= mock_model(Role, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all roles as @roles" do
      Role.stub(:all) { [mock_role] }
      get :index
      assigns(:roles).should eq([mock_role])
    end
  end

  describe "GET show" do
    it "assigns the requested role as @role" do
      Role.stub(:find_by_name).with("Something") do
        mock_role(:authorities => nil)
      end
      get :show, :name => "Something"
      assigns(:role).should be(mock_role)
    end
  end

  describe "GET edit" do
    it "assigns the requested role as @role" do
      Role.stub(:find_by_name).with("Whatever") { mock_role }
      get :edit, :name => "Whatever"
      assigns(:role).should be(mock_role)
    end
  end

end
